---
title: "Simulated Survey Results for BARUG"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)
library(lubridate)
```

```{r}
gs_auth(token='dah-token.rds', verbose = FALSE)
survey <- gs_title('Copy of BARUG August Survey (Responses)') %>% gs_read()
questions <- names(survey)
names(survey) <- c('Time', 'csvLevel', 'nBARUG', 'nMeetups', 'gs_freq', 'goodness', 'good_words', 'animal')
survey <- survey %>% filter(! grepl('I have used', csvLevel)) #remove old gs answer
```

```{r ohe_level}
survey$csvLevel <- gsub('Notebook,', 'Notebook', survey$csvLevel) #unfortunate comma in question
level_vals <- strsplit(survey$csvLevel, ',') %>% unlist() %>% unlist() %>% unique() %>% str_trim() %>% sort()
n_lev <- length(level_vals)

level_mat <- matrix(data = FALSE, nrow = nrow(survey), ncol = n_lev)
for (lev in 1:length(level_vals)) level_mat[ , lev ] <- grepl(level_vals[lev], survey$csvLevel)
colnames(level_mat) <- paste0('L', 1:n_lev)
survey <- bind_cols(survey, as.data.frame(level_mat))
survey$csvLevel <- NULL
```

```{r}
survey
```

```{r}
n_sim <- 10
clip <- function(x, min, max) ifelse(x > max, max, ifelse(x < min, min, x)) 
cap_pois <- function(n, lambda, max) clip(rpois(n, lambda), 1, max)
cap_norm <- function(n, m, s, max) clip(round(rnorm(n, m, s)), 1, max) 

vtime <- now() + hours(-n_sim:-1)
vnbarug <- cap_pois(n_sim, 4, 10)
vnmeet <- cap_pois(n_sim, 5, 10)
freq_resp <- c('Multiple times daily', 'About once a day', 'A couple time a week', 'Rarely', 'Never')
vfreq <- freq_resp[cap_pois(n_sim, 2, 5)]
vanimal <- sort(unique(survey$animal))[cap_norm(10, 3, 1.3, 5)]
vgood <- rbinom(n_sim, 1, 0.8)
vgood[sample(1:n_sim, n_sim %/% 10)] <- NA
lev_prob <- c(.9, .2, .15, .4, .1, .2, .75)
lev_sim <- matrix(nrow=n_sim, ncol = n_lev )
for (i in 1:n_lev) lev_sim[ ,i] <- rbinom(n_sim, 1, lev_prob[i])
for (i in 1:n_lev) lev_sim[ ,i] <- ifelse( lev_sim[ ,i] == 1, paste0(level_vals[i], ','), '')
lev_str <- mapply(lev_sim, 2, paste0)
     
sim <- data_frame(Time = vtime, nBARUG = vnbarug, nMeetup = vnmeet, goodness = vgood,
                  good_words = "", animal = vanimal)
```

